/*
  Define people involved
  A -- User
  B -- Doppler
  C -- App Owner
  D -- Contributor
  E -- Provider
*/

module.exports = {
  a: {
    publicKey: 'GA4O55UM6COUDSAXF6QJ766YZZFXFKOQBCJHZSXERMJAOWO7UU7WAHUK',
    secretKey: 'SBGQJHYYKH5CIQXC7FW3DC4NVEV2OSZBIOQA6OPCTOFOML674MKLWCF5',
  },
  b: {
    publicKey: 'GBBO3YJQJDANHAUYBX2EMT3H5SS6UL6AYWNVU2FOLGAEGZZ4G5WBVZBE',
    secretKey: 'SAKSPKV33WXZDR4MXKAZ2QYBXMVAYIPQJYN3U5IDTKMD7INBECOOL4ZI'
  },
  c: {
    publicKey: 'GDHNXPLOFV5CX4IKSHITQFDOBCBGPQON4SW7ODVKTDN2XA6HVJEJ4447',
  },
  d: {
    publicKey: 'GD4MEDML6X4VIFUKZXYZNTG3NKH6L2DO6O6PUTP2WRPTOFIRINIVOI4B',
  },
  e: {
    publicKey: 'GAVY57BJLR7TKAQOXTQJF5HAYG22APXOLIIVBAWU7ANM7PQ5GZZRHVUK',
  }
}
